# Generated by Django 4.2 on 2023-04-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_conversation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='users',
            new_name='members',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
